[project]
name = "rest-rpc-example-simple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rest-rpc[fastapi,requests,aiohttp,httpx,urllib3]>=0.1.0",
]

[tool.uv.sources]
rest-rpc = { workspace = true }
