[project]
name = "rest-rpc-example-simple"
version = "0.1.1"
requires-python = ">=3.12"
dependencies = [
    "rest-rpc[fastapi,requests,aiohttp,httpx,urllib3]>=0.1.0",
]

[tool.uv.sources]
rest-rpc = { workspace = true }
